### ISSUE TITLE
Blank window

### ISSUE THREAD

**Issue by securisec** [appinteractive/electron-vite-tailwind-starter#49]
I am a bit confused. I cloned the repo, and then ran `npm i -D`, followed by `npm run dev`, and I am getting a blank window with no content. Inspecting the elements in dev tools confirms this also. 

Am I missing something?

![image](https://user-images.githubusercontent.com/22226823/104832204-77cc1b80-585d-11eb-9c8a-bdf8e47c9d9e.png)

**Comment by Adam-Collier** [comment]
I got this also! In the console you get the error below. I was trying to set my own up with react but ran into this issue as well, I'm hoping there is a fix

![image](https://user-images.githubusercontent.com/20065745/106737527-b0fedc80-660e-11eb-83f1-e8ccfbf26a43.png)

**Comment by appinteractive** [comment]
@Adam-Collier @securisec That happened due to vite taking longer to start the first time. Therefore the `loadURL` method on the main window failed, I had already a timeout in plate to fix that but sometimes it took even longer than that.

Now I added a retry that loops on error until it loads (only on dev)

Does that help?

**Comment by appinteractive** [comment]
If its still happening, feel free to reopen.
